# .github/workflows/dev.yaml
name: 'Terraform - eks-dev'
on: [workflow_dispatch]

permissions:
  contents: read
  pull-requests: write

jobs: 
  plan:
    name: Plan
    env:
      TF_VAR_allowed_account_id: ${{ secrets.ALLOWED_ACCOUNT_ID }}
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::647712509431:role/GitHubAction-AssumeRoleWithAction
          aws-region: us-east-1

      - name: Initialize Terraform
        run: |
          aws s3 ls 
          cd terraform/${{ matrix.path }}
          terraform init -input=false          
