# .github/workflows/dev.yaml
name: 'Terraform - eks-dev'
on: [workflow_dispatch]

permissions:
  contents: read
  pull-requests: write

jobs: 
  terraform:
    runs-on: ubuntu-latest
    name: Terraform
    environment: dev 
    steps:
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform-version: 1.2.4
